from fastapi import APIRouter
from pydantic import BaseModel

router = APIRouter(tags=["docs"])


class DocThreshold(BaseModel):
    label: str
    value: str
    meaning: str
    action: str


class DocSubsection(BaseModel):
    id: str
    title: str
    summary: str
    how_it_works: str
    formula: str | None = None
    thresholds: list[DocThreshold] = []
    real_world: str
    tip: str


class DocSection(BaseModel):
    id: str
    title: str
    icon: str
    color: str
    intro: str
    subsections: list[DocSubsection] = []


class DocsResponse(BaseModel):
    title: str
    subtitle: str
    sections: list[DocSection]


_DOCS = DocsResponse(
    title="Platform Guide",
    subtitle="Everything you need to know to use Market Intel Platform effectively.",
    sections=[
        DocSection(
            id="getting-started",
            title="Getting Started",
            icon="Rocket",
            color="#479FFA",
            intro=(
                "Market Intel Platform ingests live price data from Finnhub and Alpha Vantage, "
                "runs technical analysis and anomaly detection in real time, and gives you "
                "Claude-powered portfolio intelligence. Here is the recommended workflow."
            ),
            subsections=[
                DocSubsection(
                    id="workflow",
                    title="Recommended Workflow",
                    summary="Follow these steps to get the most out of the platform.",
                    how_it_works=(
                        "1. Create a portfolio in the Portfolio tab and add your positions "
                        "(symbol, quantity, average cost basis). "
                        "2. Start a polling job via POST /prices/poll for the symbols you hold — "
                        "this streams live prices into the database every N seconds. "
                        "3. Use the Analytics tab to run RSI, MACD, and Bollinger Band analysis "
                        "on any symbol. "
                        "4. Watch the Alerts tab for anomaly signals generated by the detection pipeline. "
                        "5. Head to AI Insights to get Claude's full portfolio assessment and "
                        "ask natural language questions about your positions."
                    ),
                    formula=None,
                    thresholds=[],
                    real_world=(
                        "Professional traders check their dashboards at market open and close. "
                        "Use the platform the same way: run analytics in the morning, "
                        "check alerts mid-session, and review the AI summary at end of day."
                    ),
                    tip=(
                        "Keep polling intervals at 30–60 seconds during market hours. "
                        "Shorter intervals consume more API quota."
                    ),
                ),
            ],
        ),
        DocSection(
            id="indicators",
            title="Technical Indicators",
            icon="BarChart2",
            color="#4EBE96",
            intro=(
                "Technical indicators are mathematical calculations applied to price (and sometimes volume) "
                "data to help traders identify trends, momentum, and volatility. "
                "The platform computes RSI, MACD, and Bollinger Bands for any symbol with sufficient price history."
            ),
            subsections=[
                DocSubsection(
                    id="rsi",
                    title="RSI — Relative Strength Index",
                    summary=(
                        "RSI measures the speed and magnitude of recent price changes to evaluate "
                        "whether an asset is overbought or oversold on a scale of 0 to 100."
                    ),
                    how_it_works=(
                        "RSI compares the average gain to the average loss over a rolling window "
                        "(typically 14 periods). When prices have risen sharply, RSI climbs toward 100. "
                        "When prices have fallen sharply, RSI drops toward 0. The calculation is: "
                        "RS = (average gain over N periods) / (average loss over N periods), "
                        "then RSI = 100 − (100 / (1 + RS)). "
                        "This platform uses a 14-period window on minute-level price history."
                    ),
                    formula="RSI = 100 − [100 / (1 + (Avg Gain / Avg Loss))]",
                    thresholds=[
                        DocThreshold(
                            label="< 30",
                            value="Oversold",
                            meaning="The asset has fallen hard and fast. Sellers may be exhausted.",
                            action=(
                                "Look for confirmation before buying. Check if the move has a "
                                "fundamental reason (earnings miss, sector selloff). If RSI is "
                                "rising back above 30 from below, that is a classic buy entry signal."
                            ),
                        ),
                        DocThreshold(
                            label="30 – 70",
                            value="Neutral",
                            meaning="Price is within a normal oscillation range.",
                            action=(
                                "Hold existing positions. Watch for RSI approaching the extremes "
                                "or diverging from price as an early warning."
                            ),
                        ),
                        DocThreshold(
                            label="> 70",
                            value="Overbought",
                            meaning="The asset has risen fast. Buyers may be exhausted.",
                            action=(
                                "Consider trimming the position or tightening your stop-loss. "
                                "A drop back below 70 from above is a classic short entry or exit signal. "
                                "RSI can stay above 70 in strong uptrends — always use a second confirmation."
                            ),
                        ),
                    ],
                    real_world=(
                        "RSI divergence is one of the most powerful signals in technical analysis. "
                        "Bullish divergence: price makes a new low but RSI makes a higher low — "
                        "selling momentum is weakening, a reversal is likely. "
                        "Bearish divergence: price makes a new high but RSI makes a lower high — "
                        "buying momentum is fading, the rally may be near its end. "
                        "Professional traders rarely act on RSI alone. They combine it with "
                        "support/resistance levels and volume confirmation."
                    ),
                    tip=(
                        "In a strong uptrend, RSI tends to oscillate between 40 and 80 instead of "
                        "the textbook 30–70 range. Adjust your oversold threshold to 40 in bull markets."
                    ),
                ),
                DocSubsection(
                    id="macd",
                    title="MACD — Moving Average Convergence Divergence",
                    summary=(
                        "MACD tracks the relationship between two exponential moving averages to signal "
                        "trend direction, momentum shifts, and potential reversals."
                    ),
                    how_it_works=(
                        "Three components: "
                        "(1) MACD Line = 12-period EMA minus 26-period EMA. "
                        "(2) Signal Line = 9-period EMA of the MACD Line. "
                        "(3) Histogram = MACD Line minus Signal Line — shows how far apart they are. "
                        "When the 12-period EMA is above the 26-period EMA, MACD is positive (bullish momentum). "
                        "When it crosses below, MACD goes negative (bearish momentum). "
                        "This platform uses the standard 12 / 26 / 9 settings."
                    ),
                    formula=(
                        "MACD Line = EMA(12) − EMA(26)  |  "
                        "Signal = EMA(9) of MACD Line  |  "
                        "Histogram = MACD Line − Signal"
                    ),
                    thresholds=[
                        DocThreshold(
                            label="MACD crosses above Signal",
                            value="Bullish crossover",
                            meaning="Short-term momentum is accelerating upward relative to the longer-term trend.",
                            action=(
                                "This is the primary MACD buy signal. A crossover below the zero line "
                                "(both lines are negative) is a stronger signal than a crossover above zero "
                                "because it suggests a trend reversal, not just an acceleration."
                            ),
                        ),
                        DocThreshold(
                            label="MACD crosses below Signal",
                            value="Bearish crossover",
                            meaning="Short-term momentum is decelerating.",
                            action=(
                                "Primary sell/exit signal. A crossover above the zero line "
                                "is the strongest bearish signal — the trend has officially turned down."
                            ),
                        ),
                        DocThreshold(
                            label="Histogram growing",
                            value="Strengthening momentum",
                            meaning="The gap between MACD and Signal is widening — momentum is building.",
                            action="Trend followers add to positions when histogram grows consistently.",
                        ),
                        DocThreshold(
                            label="Histogram shrinking",
                            value="Weakening momentum",
                            meaning="The gap is narrowing — a crossover (and trend change) may be near.",
                            action=(
                                "Watch for a zero-line cross on the histogram. "
                                "This often precedes the actual MACD/Signal crossover by 1–2 bars."
                            ),
                        ),
                    ],
                    real_world=(
                        "The MACD histogram is the most useful part for active traders because it "
                        "gives earlier warning than the line crossover. "
                        "MACD divergence works the same as RSI divergence: if price makes a new high "
                        "but MACD histogram makes a lower high, buying pressure is fading. "
                        "Swing traders often use MACD on the daily chart as the primary trend filter "
                        "and RSI on the 4-hour chart for precise entry timing."
                    ),
                    tip=(
                        "MACD lags by definition because it is based on moving averages. "
                        "It is better at confirming a trend than predicting one. "
                        "Use it to stay in a position during a trend, not to time the exact top or bottom."
                    ),
                ),
                DocSubsection(
                    id="bollinger",
                    title="Bollinger Bands",
                    summary=(
                        "Bollinger Bands place a dynamic envelope around price using a moving average "
                        "and standard deviation, making it easy to see whether price is extended "
                        "relative to recent volatility."
                    ),
                    how_it_works=(
                        "Three lines are plotted: "
                        "(1) Middle Band = 20-period simple moving average (SMA). "
                        "(2) Upper Band = Middle + (2 × standard deviation of last 20 closes). "
                        "(3) Lower Band = Middle − (2 × standard deviation). "
                        "Bandwidth = (Upper − Lower) / Middle — measures how wide the bands are. "
                        "This platform uses the standard 20-period, 2-standard-deviation settings."
                    ),
                    formula=(
                        "Middle = SMA(20)  |  "
                        "Upper = SMA(20) + 2σ  |  "
                        "Lower = SMA(20) − 2σ  |  "
                        "Bandwidth = (Upper − Lower) / Middle"
                    ),
                    thresholds=[
                        DocThreshold(
                            label="Price touches Upper Band",
                            value="Relatively overbought",
                            meaning="Price is 2 standard deviations above the recent average — statistically unusual.",
                            action=(
                                "In a ranging market this is a sell signal. "
                                "In a strong uptrend, price can 'walk the upper band' — "
                                "this means the trend is very strong. "
                                "Wait for price to close back inside the band before calling a top."
                            ),
                        ),
                        DocThreshold(
                            label="Price touches Lower Band",
                            value="Relatively oversold",
                            meaning="Price is 2 standard deviations below the recent average.",
                            action=(
                                "In a ranging market this is a buy signal. "
                                "In a strong downtrend, price can walk the lower band. "
                                "Combine with RSI < 30 for high-conviction oversold entries."
                            ),
                        ),
                        DocThreshold(
                            label="Low Bandwidth (Squeeze)",
                            value="Volatility contraction",
                            meaning="Bands are very narrow — the market is coiling for a breakout.",
                            action=(
                                "The Bollinger Squeeze is one of the most reliable setups. "
                                "After a prolonged squeeze, position yourself in the direction "
                                "of the first significant candle that breaks above or below the bands. "
                                "Set a tight stop on the opposite band."
                            ),
                        ),
                        DocThreshold(
                            label="High Bandwidth (Expansion)",
                            value="High volatility",
                            meaning="A big move is in progress.",
                            action=(
                                "Trend-following strategies work well during band expansion. "
                                "Do not try to fade the move — wide bands mean strong momentum."
                            ),
                        ),
                    ],
                    real_world=(
                        "The Bollinger Squeeze is the most traded Bollinger Band setup. "
                        "When bandwidth reaches a multi-month low, professional traders prepare "
                        "for a breakout by placing buy stops above the upper band and sell stops "
                        "below the lower band. The direction of the breakout determines the trade. "
                        "Many algorithmic systems use Bollinger Bands as a volatility filter — "
                        "only taking RSI or MACD signals when bandwidth is above a minimum threshold."
                    ),
                    tip=(
                        "Bollinger Bands adapt to volatility automatically. They are tighter during "
                        "calm periods and wider during volatile ones — this makes them more robust "
                        "than static support/resistance levels across different market conditions."
                    ),
                ),
            ],
        ),
        DocSection(
            id="signals",
            title="Trading Signals",
            icon="Zap",
            color="#F59E0B",
            intro=(
                "The platform synthesises RSI, MACD, and Bollinger Band readings into a single "
                "BUY / SELL / HOLD signal with a confidence score (0–100%). "
                "The signal is generated by a majority-vote system across all three indicators."
            ),
            subsections=[
                DocSubsection(
                    id="signal-engine",
                    title="How Signals Are Generated",
                    summary="A voting system weights each indicator's reading to produce a consensus signal.",
                    how_it_works=(
                        "Each indicator casts a vote: "
                        "RSI votes BUY if < 40, SELL if > 60, otherwise HOLD. "
                        "MACD votes BUY if line > signal (positive histogram), SELL if line < signal. "
                        "Bollinger votes BUY if price < lower band, SELL if price > upper band. "
                        "The signal with the most votes wins. "
                        "Confidence = (number of agreeing votes / 3) × 100%. "
                        "A 3/3 unanimous signal has 100% confidence. A 2/3 majority has 67% confidence. "
                        "A 1/3 split results in HOLD regardless of the winning vote."
                    ),
                    formula="Confidence = (agreeing votes / 3) × 100%",
                    thresholds=[
                        DocThreshold(
                            label="BUY — 100%",
                            value="Strong buy",
                            meaning="All three indicators agree the asset is oversold or gaining momentum.",
                            action=(
                                "High-conviction entry. Still check broader market context "
                                "and ensure the position fits your portfolio risk limits."
                            ),
                        ),
                        DocThreshold(
                            label="BUY — 67%",
                            value="Moderate buy",
                            meaning="Two of three indicators lean bullish.",
                            action="Consider a partial entry. Scale in if the third indicator confirms.",
                        ),
                        DocThreshold(
                            label="HOLD",
                            value="No clear edge",
                            meaning="Indicators are mixed or neutral.",
                            action="Do nothing. Wait for a clearer setup rather than forcing a trade.",
                        ),
                        DocThreshold(
                            label="SELL — 67%",
                            value="Moderate sell",
                            meaning="Two of three indicators lean bearish.",
                            action="Consider reducing the position by 25–50%. Watch the third indicator.",
                        ),
                        DocThreshold(
                            label="SELL — 100%",
                            value="Strong sell",
                            meaning="All three indicators agree the asset is overbought or losing momentum.",
                            action=(
                                "Exit or significantly reduce the position. "
                                "If short-selling, this is a high-conviction entry."
                            ),
                        ),
                    ],
                    real_world=(
                        "No signal system is infallible. Use the signal as a starting point, "
                        "not a final decision. Professional traders ask: does this signal make sense "
                        "given the broader market regime (risk-on vs risk-off), sector rotation, "
                        "and any upcoming catalysts (earnings, Fed meetings, macro data)?' "
                        "The AI Insights tab answers exactly these questions."
                    ),
                    tip=(
                        "A HOLD signal from this system does not mean 'safe to hold indefinitely'. "
                        "It means the technical evidence is inconclusive right now. "
                        "Check back after the next price update."
                    ),
                ),
            ],
        ),
        DocSection(
            id="alerts",
            title="Alerts & Anomaly Detection",
            icon="Bell",
            color="#D84F68",
            intro=(
                "The anomaly detection pipeline runs continuously in a separate Kafka consumer. "
                "It flags abnormal price behaviour using two independent methods: "
                "z-score statistical analysis and moving average divergence."
            ),
            subsections=[
                DocSubsection(
                    id="zscore",
                    title="Z-Score Anomaly",
                    summary=(
                        "A z-score measures how many standard deviations the current price is "
                        "from the rolling mean of the last 20 prices."
                    ),
                    how_it_works=(
                        "For every incoming price tick, the system calculates the mean and "
                        "standard deviation of the last 20 price points for that symbol. "
                        "Z-score = (current price − rolling mean) / rolling standard deviation. "
                        "A z-score of +2 means the price is 2 standard deviations above the recent average. "
                        "This is statistically unusual — it happens roughly 5% of the time in a normal distribution. "
                        "The system uses two severity thresholds: ±3σ for HIGH and ±4σ for CRITICAL."
                    ),
                    formula="Z = (Price − μ) / σ   where μ and σ are computed over the last 20 ticks",
                    thresholds=[
                        DocThreshold(
                            label="|Z| > 3σ",
                            value="HIGH severity",
                            meaning="Price is 3 standard deviations from the recent mean. Statistically, this happens < 0.3% of the time.",
                            action=(
                                "Investigate immediately. Check recent news, earnings releases, or "
                                "macro events for the symbol. If no fundamental reason exists, "
                                "this may be a data feed spike — wait for confirmation."
                            ),
                        ),
                        DocThreshold(
                            label="|Z| > 4σ",
                            value="CRITICAL severity",
                            meaning="Extreme deviation — < 0.006% probability in a normal distribution. Almost always has a cause.",
                            action=(
                                "Act immediately. This level of deviation usually indicates a major news event, "
                                "circuit breaker trigger, or halt and resume. "
                                "If you hold this position, consider hedging or reducing until you understand the cause."
                            ),
                        ),
                    ],
                    real_world=(
                        "Z-score alerts are widely used in quantitative trading as part of pairs trading "
                        "and statistical arbitrage strategies. When the z-score of a spread between two "
                        "correlated assets reaches ±2, quant funds open mean-reversion trades betting "
                        "the spread will return to zero. Here, the z-score is applied to raw price, "
                        "which is more suited to catching sudden intraday shocks."
                    ),
                    tip=(
                        "High z-score alerts early in the trading session (within the first 15 minutes) "
                        "are often driven by the gap between yesterday's close and today's open. "
                        "These gaps are common and do not always signal a tradeable anomaly."
                    ),
                ),
                DocSubsection(
                    id="ma-divergence",
                    title="Moving Average Divergence",
                    summary=(
                        "This alert fires when a fast moving average diverges significantly from "
                        "a slow moving average, signalling a potential trend change."
                    ),
                    how_it_works=(
                        "The system maintains a 5-period moving average for each symbol. "
                        "When the most recent MA and the previous MA diverge by more than 0.5%, "
                        "an alert is raised. This is a simpler, faster signal than MACD — "
                        "it catches rapid momentum shifts that may not yet show up in longer indicators."
                    ),
                    formula="Divergence % = |Fast MA − Slow MA| / Slow MA × 100",
                    thresholds=[
                        DocThreshold(
                            label="> 0.5% divergence",
                            value="MA Divergence alert",
                            meaning="Short-term momentum has shifted significantly from its recent baseline.",
                            action=(
                                "Cross-reference with the RSI and MACD signals in the Analytics tab. "
                                "If all three are aligned, this is a high-conviction momentum signal. "
                                "If only MA divergence is firing, treat it as a warning to monitor more closely."
                            ),
                        ),
                    ],
                    real_world=(
                        "MA divergence alerts are similar to the early-warning system used by "
                        "high-frequency trading desks. They do not necessarily signal a reversal — "
                        "sometimes they confirm an acceleration of the existing trend. "
                        "Always ask: is this divergence going with or against the prevailing trend?"
                    ),
                    tip=(
                        "Use the Resolve button to dismiss an alert once you have investigated it. "
                        "Keeping resolved alerts in the list makes it harder to spot new ones."
                    ),
                ),
                DocSubsection(
                    id="acting-on-alerts",
                    title="How to Act on Alerts",
                    summary="A structured process for evaluating and responding to anomaly alerts.",
                    how_it_works=(
                        "Step 1 — Verify: Is the price move real or a data feed error? "
                        "Check a second data source (Finnhub vs Alpha Vantage on the Dashboard). "
                        "Step 2 — Find the cause: Check financial news for the symbol. "
                        "Earnings, analyst upgrades/downgrades, macro data, and sector news "
                        "are the most common causes. "
                        "Step 3 — Assess your exposure: How large is this position relative to the portfolio? "
                        "Check the Portfolio tab for the weight. "
                        "Step 4 — Decide: If the move has a legitimate fundamental reason and aligns "
                        "with your thesis, hold or add. If the move has no clear reason, reduce. "
                        "If it is a critical anomaly against your position, hedge immediately. "
                        "Step 5 — Resolve the alert to keep your queue clean."
                    ),
                    formula=None,
                    thresholds=[],
                    real_world=(
                        "Professional risk managers follow a similar checklist. The key principle is: "
                        "never add to a losing position because of an alert alone. "
                        "Alerts tell you something unusual happened — they do not tell you what to do. "
                        "The decision always depends on your position size, time horizon, and risk tolerance."
                    ),
                    tip=(
                        "Critical alerts on high-weight positions (> 20% of portfolio) should always "
                        "be treated as stop-everything events until you understand what triggered them."
                    ),
                ),
            ],
        ),
        DocSection(
            id="risk",
            title="Risk Metrics",
            icon="Shield",
            color="#A78BFA",
            intro=(
                "The Portfolio Analytics endpoint computes four risk metrics using numpy: "
                "Value at Risk (VaR), Sharpe Ratio, Maximum Drawdown, and a Correlation Matrix. "
                "These are the same metrics used by professional portfolio managers."
            ),
            subsections=[
                DocSubsection(
                    id="var",
                    title="Value at Risk (VaR 95%)",
                    summary=(
                        "VaR estimates the maximum loss your portfolio could suffer on a single day "
                        "with 95% confidence, based on the historical distribution of returns."
                    ),
                    how_it_works=(
                        "The system collects the daily return distribution of the portfolio's value. "
                        "VaR at 95% confidence = the 5th percentile of that distribution. "
                        "This means: on 95% of days, the portfolio will not lose more than this amount. "
                        "On 5% of days (about 12 trading days per year), the loss could exceed VaR. "
                        "The platform uses parametric VaR (assuming a normal return distribution)."
                    ),
                    formula="VaR (95%) = Portfolio Value × (μ − 1.645σ)   where μ = mean daily return, σ = std dev",
                    thresholds=[
                        DocThreshold(
                            label="VaR < 1%",
                            value="Low risk",
                            meaning="The portfolio is well-diversified or positioned conservatively.",
                            action="Suitable for capital preservation strategies. May underperform in bull markets.",
                        ),
                        DocThreshold(
                            label="VaR 1–3%",
                            value="Moderate risk",
                            meaning="Normal range for an equity-heavy portfolio.",
                            action="Acceptable for long-term growth strategies. Monitor during high-volatility periods.",
                        ),
                        DocThreshold(
                            label="VaR > 5%",
                            value="High risk",
                            meaning="The portfolio is concentrated or holding volatile assets.",
                            action=(
                                "Review position sizing. Consider hedging the largest positions. "
                                "A 5% daily VaR implies a realistic possibility of 10–20% drawdowns."
                            ),
                        ),
                    ],
                    real_world=(
                        "VaR is required reporting for banks and hedge funds under Basel III regulations. "
                        "However, VaR has a famous limitation: it tells you nothing about the losses "
                        "beyond the 5% threshold (the 'tail risk'). The 2008 financial crisis showed "
                        "that tail losses can be many times larger than VaR suggested. "
                        "For this reason, sophisticated risk managers use VaR alongside stress tests."
                    ),
                    tip=(
                        "VaR is only as good as the return history behind it. "
                        "If your price history is short (< 30 days), the VaR estimate is unreliable. "
                        "Build up price history by running polling jobs for several weeks before "
                        "making risk decisions based on VaR."
                    ),
                ),
                DocSubsection(
                    id="sharpe",
                    title="Sharpe Ratio",
                    summary=(
                        "The Sharpe Ratio measures how much return you are earning per unit of risk. "
                        "It is the most widely used metric for comparing portfolio performance."
                    ),
                    how_it_works=(
                        "Sharpe = (Portfolio Return − Risk-Free Rate) / Portfolio Standard Deviation. "
                        "The platform uses a 0% risk-free rate for simplicity "
                        "(in practice you would use the current T-bill yield). "
                        "A higher Sharpe ratio means you are being better compensated for the risk you are taking."
                    ),
                    formula="Sharpe = (Rp − Rf) / σp   where Rp = portfolio return, Rf = risk-free rate, σp = std dev",
                    thresholds=[
                        DocThreshold(
                            label="< 0",
                            value="Negative — losing money",
                            meaning="The portfolio is underperforming even a zero-yield investment.",
                            action="Urgently review all positions. Consider moving to cash or hedging.",
                        ),
                        DocThreshold(
                            label="0 – 1",
                            value="Sub-optimal",
                            meaning="The portfolio earns some return but the risk is not well compensated.",
                            action="Look for lower-correlation positions to improve diversification.",
                        ),
                        DocThreshold(
                            label="1 – 2",
                            value="Good",
                            meaning="Solid risk-adjusted performance. Better than most actively managed funds.",
                            action="Maintain the strategy. Look for opportunities to incrementally improve.",
                        ),
                        DocThreshold(
                            label="> 2",
                            value="Excellent",
                            meaning="Exceptional risk-adjusted return. Difficult to sustain long-term.",
                            action="Enjoy it, but do not over-leverage. Mean reversion is real.",
                        ),
                    ],
                    real_world=(
                        "Institutional investors use the Sharpe Ratio to compare managers. "
                        "Warren Buffett's Berkshire Hathaway has historically averaged a Sharpe of ~0.76. "
                        "Renaissance Technologies' Medallion Fund reportedly achieves Sharpe > 2 consistently — "
                        "widely considered the best long-term risk-adjusted track record in the world. "
                        "For retail traders, a Sharpe above 1 over a full market cycle is genuinely impressive."
                    ),
                    tip=(
                        "Sharpe Ratio is annualised when comparing across portfolios. "
                        "If your data is minute-level, multiply the daily Sharpe by √252 to get the annual figure."
                    ),
                ),
                DocSubsection(
                    id="drawdown",
                    title="Maximum Drawdown",
                    summary=(
                        "Maximum drawdown measures the largest peak-to-trough decline in portfolio value. "
                        "It is the most intuitive measure of downside risk."
                    ),
                    how_it_works=(
                        "The system tracks the running portfolio value and records the largest percentage "
                        "decline from any peak to the subsequent trough before a new peak is set. "
                        "A max drawdown of −15% means the portfolio fell 15% from its highest point "
                        "before recovering."
                    ),
                    formula="Max Drawdown = (Trough Value − Peak Value) / Peak Value × 100%",
                    thresholds=[
                        DocThreshold(
                            label="0 – 5%",
                            value="Minimal drawdown",
                            meaning="Very low volatility or a short history.",
                            action="Acceptable. Could indicate insufficient risk (missing return opportunities).",
                        ),
                        DocThreshold(
                            label="5 – 20%",
                            value="Normal drawdown",
                            meaning="Typical range for a diversified equity portfolio.",
                            action="Within normal parameters. Monitor for sustained drawdown duration.",
                        ),
                        DocThreshold(
                            label="> 20%",
                            value="Severe drawdown",
                            meaning="The portfolio has experienced a significant decline.",
                            action=(
                                "Evaluate whether the underlying thesis for each position still holds. "
                                "A drawdown above 20% often indicates a structural problem, "
                                "not just short-term volatility."
                            ),
                        ),
                    ],
                    real_world=(
                        "The S&P 500 experienced a max drawdown of −57% during the 2008 financial crisis "
                        "and −34% during the 2020 COVID crash. Drawdown duration matters as much as depth: "
                        "investors who stayed invested through 2008 recovered within 4 years. "
                        "Many retail traders psychologically cannot tolerate drawdowns above 20–25% "
                        "and capitulate at the worst possible moment."
                    ),
                    tip=(
                        "Your maximum tolerable drawdown determines your maximum position sizing. "
                        "If you cannot stomach more than a 10% portfolio loss, "
                        "your single-position size should probably not exceed 5–10%."
                    ),
                ),
                DocSubsection(
                    id="correlation",
                    title="Correlation Matrix",
                    summary=(
                        "The correlation matrix shows how closely each pair of positions moves together. "
                        "High correlation means poor diversification."
                    ),
                    how_it_works=(
                        "The system calculates the Pearson correlation coefficient between the daily "
                        "return series of every pair of positions in the portfolio. "
                        "Values range from −1 (perfectly inverse) to +1 (perfectly correlated). "
                        "A well-diversified portfolio has many low or negative correlations between positions."
                    ),
                    formula="ρ(X,Y) = Cov(X,Y) / (σX × σY)   where ρ ∈ [−1, +1]",
                    thresholds=[
                        DocThreshold(
                            label="ρ > 0.8",
                            value="High positive correlation",
                            meaning="The two positions behave almost identically — you are taking the same bet twice.",
                            action="Consider replacing one with a less correlated asset, or treat them as one position.",
                        ),
                        DocThreshold(
                            label="0.3 < ρ < 0.8",
                            value="Moderate correlation",
                            meaning="Positions tend to move in the same direction but not in lockstep.",
                            action="Acceptable. Ensure no single market factor (e.g. Fed rate decisions) drives all of them.",
                        ),
                        DocThreshold(
                            label="−0.3 < ρ < 0.3",
                            value="Low / no correlation",
                            meaning="Positions are largely independent — genuine diversification.",
                            action="This is the goal. These positions provide real risk reduction.",
                        ),
                        DocThreshold(
                            label="ρ < −0.3",
                            value="Negative correlation",
                            meaning="Positions tend to move in opposite directions — a natural hedge.",
                            action=(
                                "Useful for defensive portfolios. "
                                "Note that negative correlation can disappear in crisis periods "
                                "when all assets become correlated."
                            ),
                        ),
                    ],
                    real_world=(
                        "During the 2008 crisis, correlations between almost all equity assets "
                        "converged toward +1 — the only things that remained negatively correlated "
                        "were US Treasuries and gold. This is why institutional investors use "
                        "'risk-on / risk-off' correlation matrices — one for normal markets "
                        "and one for stress scenarios."
                    ),
                    tip=(
                        "Tech stocks (AAPL, NVDA, MSFT, GOOGL) are typically highly correlated "
                        "with each other. Holding all four provides less diversification than "
                        "the number of positions suggests."
                    ),
                ),
            ],
        ),
        DocSection(
            id="analytics",
            title="Using Analytics",
            icon="Activity",
            color="#22D3EE",
            intro=(
                "The Analytics tab is your technical analysis workbench. "
                "Enter any symbol with an active polling job to see its full indicator profile."
            ),
            subsections=[
                DocSubsection(
                    id="analytics-workflow",
                    title="Analytics Workflow",
                    summary="How to use the Analytics page effectively for real trading decisions.",
                    how_it_works=(
                        "1. Enter a symbol in the search box and press Enter (or click Analyze). "
                        "The platform fetches the last 100 price points and computes all indicators. "
                        "2. Read the Signal Banner first — it summarises the overall technical verdict "
                        "and confidence level. "
                        "3. Check the Price History chart with Bollinger Band overlays. "
                        "Is price near the upper or lower band? Are the bands wide or narrow? "
                        "4. Look at the RSI gauge. Confirm the reading aligns with the signal. "
                        "5. Review the MACD panel. Is the histogram positive or negative? Growing or shrinking? "
                        "6. Cross-reference with active alerts for the same symbol in the Alerts tab. "
                        "7. If the signal is high-confidence and aligns with no critical alerts, "
                        "check the AI Insights tab for the portfolio-level context before acting."
                    ),
                    formula=None,
                    thresholds=[],
                    real_world=(
                        "Professional analysts call this process 'confluence' — when multiple "
                        "independent signals all point in the same direction, the probability "
                        "of a successful trade increases. "
                        "A BUY signal with 100% confidence + RSI at 28 + price at the lower Bollinger Band "
                        "+ a MACD bullish crossover = very high confluence. "
                        "A BUY signal with 67% confidence + RSI at 45 = low confluence, low priority."
                    ),
                    tip=(
                        "Use the quick-symbol buttons (AAPL, NVDA, TSLA, MSFT, GOOGL) to rapidly "
                        "scan across all major positions. Build a habit of checking analytics "
                        "on all your positions in sequence each morning."
                    ),
                ),
            ],
        ),
        DocSection(
            id="portfolio",
            title="Portfolio Management",
            icon="Briefcase",
            color="#4EBE96",
            intro=(
                "The Portfolio tab lets you track positions, monitor live P&L, "
                "and view risk-adjusted performance metrics. "
                "All P&L calculations use live prices fetched in real time."
            ),
            subsections=[
                DocSubsection(
                    id="positions",
                    title="Managing Positions",
                    summary="How to add, update, and close positions.",
                    how_it_works=(
                        "Add Position: Enter the symbol, quantity, and your average cost basis (price per share). "
                        "The platform will calculate your unrealised P&L using the latest price. "
                        "Update a Position: Adding the same symbol again will update the existing position "
                        "(quantity and cost basis are replaced, not averaged). "
                        "Close a Position: Click the X button on any position row. "
                        "This marks the position as closed and removes it from P&L calculations. "
                        "The platform does not execute real trades — it only tracks them."
                    ),
                    formula="Unrealised P&L = (Current Price − Avg Cost Basis) × Quantity",
                    thresholds=[],
                    real_world=(
                        "Tracking positions here mirrors what professional trading desks call a 'blotter'. "
                        "The key metric is P&L as a percentage of total portfolio value (weight-adjusted return), "
                        "not raw dollar P&L. A $5,000 gain on a $10,000 position is more significant "
                        "than a $5,000 gain on a $100,000 position."
                    ),
                    tip=(
                        "Enter your real average cost basis accurately. "
                        "The AI Insights analysis uses cost basis to calculate realised and unrealised performance, "
                        "which affects the quality of the Claude recommendations."
                    ),
                ),
            ],
        ),
    ],
)


@router.get("/guide", response_model=DocsResponse)
async def get_guide() -> DocsResponse:
    return _DOCS
